import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { and, eq, notExists, notInArray, or, sql } from 'drizzle-orm'

import type { DbConnection } from '../index'
import { lineModeEnum, lines, lineStations } from '../schema/lines'
import { networks } from '../schema/networks'
import { reports } from '../schema/reports'
import { stations } from '../schema/stations'

/** Directory holding one subdirectory per network, each generated by `scripts/build_network.py`. */
const NETWORKS_DIR = join(import.meta.dir, 'networks')

interface StationData {
    coordinates: {
        latitude: number
        longitude: number
    }
    lines: string[]
    name: string
}

type StationsMap = Record<string, StationData>

type LinesMap = Record<string, string[]>

/** `LineMetadata.json`, generated from OpenStreetMap by `scripts/create_line_metadata.py`. */
/* The value is optional because this comes from a file on disk: a lookup can miss, whatever the
   shape claims. */
type LineMetadataMap = Record<
    string,
    { color: string; mode: (typeof lineModeEnum.enumValues)[number]; isCircular: boolean } | undefined
>

/**
 * `network.json` as written by the build script. It is the machine readable projection of the
 * network's YAML description in `networks/`, so the backend never has to parse YAML.
 */
interface NetworkMetadata {
    id: string
    name: string
    countryCode: string
    timezone: string
    status: 'active' | 'beta'
    /** The other cities the network reaches, generated from its stations. Absent on data built
        before the reach step existed, which reads the same as "none". */
    serves?: string[]
    center: { latitude: number; longitude: number }
    bounds: {
        southWest: { latitude: number; longitude: number }
        northEast: { latitude: number; longitude: number }
    }
}

interface NetworkSeedData {
    metadata: NetworkMetadata
    stations: StationsMap
    lines: LinesMap
    lineMetadata: LineMetadataMap
}

const readJson = <T>(directory: string, file: string): T => {
    try {
        return JSON.parse(readFileSync(join(directory, file), 'utf-8')) as T
    } catch (error) {
        throw new Error(
            `Could not read ${file} in ${directory}. Generate it with "python3 scripts/build_network.py --network <id>".`,
            { cause: error }
        )
    }
}

/**
 * Station ids have to be unique across every network, because a station belongs to exactly one.
 *
 * Checked here rather than left to the database: the insert below matches on the id alone, so a
 * second network claiming an id would silently overwrite the first network's name and coordinates
 * and only fail later, on a foreign key whose message names neither network. `validate_network.py`
 * rejects the same case in CI, this is the second line of defence for data that reaches a database
 * anyway.
 */
const assertStationIdsAreUniqueAcrossNetworks = (networks: NetworkSeedData[]) => {
    const owner = new Map<string, string>()

    for (const network of networks) {
        for (const stationId of Object.keys(network.stations)) {
            const existingOwner = owner.get(stationId)
            if (existingOwner !== undefined) {
                throw new Error(
                    `Station id '${stationId}' is claimed by both '${existingOwner}' and ` +
                        `'${network.metadata.id}'. A station belongs to exactly one network.`
                )
            }
            owner.set(stationId, network.metadata.id)
        }
    }
}

/**
 * Read every network that ships seed data.
 *
 * Networks are discovered from the filesystem rather than listed in code, so adding a city means
 * adding its data directory and nothing else. Reading at runtime instead of importing the JSON keeps
 * the set dynamic; the files are only a few hundred kilobytes each.
 */
const readNetworks = (): NetworkSeedData[] => {
    const directories = readdirSync(NETWORKS_DIR, { withFileTypes: true }).filter((entry) => entry.isDirectory())

    const networks = directories.map((entry) => {
        const directory = join(NETWORKS_DIR, entry.name)
        const metadata = readJson<NetworkMetadata>(directory, 'network.json')

        if (metadata.id !== entry.name) {
            throw new Error(`${directory}/network.json declares id '${metadata.id}' but lives in '${entry.name}'`)
        }

        return {
            metadata,
            stations: readJson<StationsMap>(directory, 'StationsList.json'),
            lines: readJson<LinesMap>(directory, 'LinesList.json'),
            lineMetadata: readJson<LineMetadataMap>(directory, 'LineMetadata.json'),
        }
    })

    assertStationIdsAreUniqueAcrossNetworks(networks)

    return networks
}

const toNetworkRecord = (metadata: NetworkMetadata) => ({
    id: metadata.id,
    name: metadata.name,
    countryCode: metadata.countryCode,
    timezone: metadata.timezone,
    status: metadata.status,
    serves: metadata.serves ?? [],
    centerLat: metadata.center.latitude,
    centerLng: metadata.center.longitude,
    boundsSwLat: metadata.bounds.southWest.latitude,
    boundsSwLng: metadata.bounds.southWest.longitude,
    boundsNeLat: metadata.bounds.northEast.latitude,
    boundsNeLng: metadata.bounds.northEast.longitude,
})

/**
 * Removes the lines of a network that the regenerated data no longer contains.
 *
 * An upsert alone only ever adds, so a discontinued line would keep its row and be served with an
 * empty station list, which clients draw as a line that exists but goes nowhere.
 *
 * A line that reports still point at is kept on purpose. Its foreign key is deliberately not
 * cascading, and a report is the one thing here that is not regenerable: throwing away a piece of
 * the history because a line was renamed would be a worse outcome than an extra row. Such a line
 * disappears once its reports have aged out of the retention window.
 */
const deleteRemovedLines = async (db: DbConnection, networkId: string, currentLineIds: string[]) => {
    await db.delete(lines).where(
        and(
            eq(lines.networkId, networkId),
            currentLineIds.length > 0 ? notInArray(lines.id, currentLineIds) : undefined,
            notExists(
                db
                    .select({ exists: sql`1` })
                    .from(reports)
                    .where(and(eq(reports.networkId, networkId), eq(reports.lineId, lines.id)))
            )
        )
    )
}

/**
 * Removes the stations of a network that the regenerated data no longer contains.
 *
 * Same reasoning as for lines, and the same exception: a station a report names, as its station or
 * as its direction, is kept so that the report survives. Since `line_stations` was cleared before
 * this runs, a kept station is served without any lines rather than with a stale set.
 */
const deleteRemovedStations = async (db: DbConnection, networkId: string, currentStationIds: string[]) => {
    await db.delete(stations).where(
        and(
            eq(stations.networkId, networkId),
            currentStationIds.length > 0 ? notInArray(stations.id, currentStationIds) : undefined,
            notExists(
                db
                    .select({ exists: sql`1` })
                    .from(reports)
                    .where(
                        and(
                            eq(reports.networkId, networkId),
                            or(eq(reports.stationId, stations.id), eq(reports.directionId, stations.id))
                        )
                    )
            )
        )
    )
}

/**
 * Insert the transit data of every network.
 *
 * Written network by network so that a failure names the city that caused it, and inserted in
 * dependency order because the composite foreign keys require the network and the stations to exist
 * before a line can refer to them.
 *
 * The removals of one pass all happen before the writes of the next, because a station can move
 * between networks from one generation of the data to the next, and the rows still pointing at it
 * under its old network would otherwise block the move.
 */
export const seedBaseData = async (db: DbConnection) => {
    const networksToSeed = readNetworks()

    for (const network of networksToSeed) {
        const networkId = network.metadata.id

        /* Updated rather than skipped on conflict. This data is generated from OpenStreetMap and
           regenerated when a city's network changes, so re-seeding has to bring the database up to
           date. Skipping would silently keep a renamed station or a corrected colour out. */
        const networkRecord = toNetworkRecord(network.metadata)
        await db
            .insert(networks)
            .values(networkRecord)
            .onConflictDoUpdate({
                target: networks.id,
                set: {
                    name: sql`excluded.name`,
                    countryCode: sql`excluded.country_code`,
                    timezone: sql`excluded.timezone`,
                    status: sql`excluded.status`,
                    serves: sql`excluded.serves`,
                    centerLat: sql`excluded.center_lat`,
                    centerLng: sql`excluded.center_lng`,
                    boundsSwLat: sql`excluded.bounds_sw_lat`,
                    boundsSwLng: sql`excluded.bounds_sw_lng`,
                    boundsNeLat: sql`excluded.bounds_ne_lat`,
                    boundsNeLng: sql`excluded.bounds_ne_lng`,
                },
            })

        /* Replaced rather than upserted. An upsert alone only ever adds: a station that the
           regenerated data no longer lists on a line would keep its old row, and with it its old
           order, which is how a dropped stop ends up as a line's terminus and misdirects the
           direction inference. Nothing references `line_stations`, so deleting first is safe. */
        await db.delete(lineStations).where(eq(lineStations.networkId, networkId))
    }

    for (const network of networksToSeed) {
        const networkId = network.metadata.id
        const stationIds = Object.keys(network.stations)
        const lineIds = Object.keys(network.lines)

        await deleteRemovedLines(db, networkId, lineIds)
        await deleteRemovedStations(db, networkId, stationIds)

        const stationRecords = Object.entries(network.stations).map(([id, data]) => ({
            id,
            networkId,
            name: data.name,
            lat: data.coordinates.latitude,
            lng: data.coordinates.longitude,
        }))

        await db
            .insert(stations)
            .values(stationRecords)
            .onConflictDoUpdate({
                target: stations.id,
                set: {
                    /* The network is part of the update, not just the payload. Station ids are
                       globally unique, so a station that a new generation of the data assigns to
                       another network conflicts with its own old row: without this it would keep
                       the network it no longer belongs to and be invisible under the new one.
                       A station that reports still point at cannot move, the foreign key on
                       `reports` refuses it. That is deliberate: silently moving it would strand its
                       reports in a network the station is no longer part of. */
                    networkId: sql`excluded.network_id`,
                    name: sql`excluded.name`,
                    lat: sql`excluded.lat`,
                    lng: sql`excluded.lng`,
                },
            })

        const lineRecords = lineIds.map((id) => {
            /* Required rather than defaulted. A line without metadata would be drawn black and
               filtered into no category at all, which is harder to notice than a failed seed.
               `scripts/validate_network.py` rejects the same case in CI. */
            const metadata = network.lineMetadata[id]
            if (metadata === undefined) {
                throw new Error(`${networkId}: LineMetadata.json has no entry for line '${id}'`)
            }

            return { id, networkId, name: id, ...metadata }
        })

        await db
            .insert(lines)
            .values(lineRecords)
            .onConflictDoUpdate({
                target: [lines.networkId, lines.id],
                set: {
                    name: sql`excluded.name`,
                    isCircular: sql`excluded.is_circular`,
                    color: sql`excluded.color`,
                    mode: sql`excluded.mode`,
                },
            })

        const stationLineRecords = Object.entries(network.lines).flatMap(([lineId, lineStationIds]) =>
            lineStationIds.map((stationId, order) => ({ networkId, stationId, lineId, order }))
        )

        await db.insert(lineStations).values(stationLineRecords)
    }
}
